BUG: Can't immediately search for graduate courses
ucsb-cs156-w24/proj-courses-w24-5pm-2 pull request #17
Opened 2024-02-28 09:25 UTC by jiaqiguan2003

In this PR we fixed can't immediately search for graduate courses when you click submit on the first try: "When I first attempt to view graduate-only courses, the search returns undergraduate courses as well."

With this change, we should now be able to:
- view graduate-only courses on my first try after refreshing the page.
- view any other level courses on my first try.

<img width="1413" alt="Screen Shot 2024-02-28 at 1 22 11 AM" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/assets/124765197/0cdca922-9b65-446d-9ca8-ca9eb071773c">

2024-02-29 00:17 UTC, tallyhawley requested changes
Please include a link to your Dokku deployment showing these changes

2024-02-29 01:24 UTC, jiaqiguan2003 commented
> Please include a link to your Dokku deployment showing these changes

http://courses-qa.dokku-06.cs.ucsb.edu
https://courses-qa.dokku-06.cs.ucsb.edu

2024-02-29 01:52 UTC, Maria-Saucedo approved these changes, later dismissed
LGTM

2024-03-01 00:40 UTC, AnikaArora submitted a review, later dismissed
I think your branches got messed up a bit because I see changes for the "Developer Info" dropdown in this PR. Could you please make sure that this PR only has the changes for this specific bug/issue?

2024-03-01 01:19 UTC, Maria-Saucedo approved these changes, later dismissed
The branch looks correct now, LGTM

2024-03-01 02:22 UTC, tallyhawley requested changes
Could you add tests making sure that this functionality works as expected?

2024-03-03 23:16 UTC, Maria-Saucedo approved these changes
LGTM

2024-03-06 01:10 UTC, tallyhawley approved these changes
Looks good to me, :shipit:

2024-03-06 01:11 UTC, merged