Jh Add Course From Search
ucsb-cs156-w24/proj-courses-w24-5pm-2 pull request #27
Opened 2024-03-08 00:13 UTC by jonathan-herring

In this PR, we add an add button for sections that allows users to add sections to one of their selected schedules

2024-03-11 06:41 UTC, jiaqiguan2003 submitted a review, later dismissed
deployed the branch at: https://courses-jiaqiguan2003-dev.dokku-06.cs.ucsb.edu

all functions worked as expected! LGTM

2024-03-11 07:17 UTC, Maria-Saucedo approved these changes, later dismissed
LGTM

2024-03-11 09:05 UTC, tallyhawley requested changes
1. There is a bug where clicking "add" for the first time after logging in (or refreshing?) causes the "no schedule/ create a schedule" text to pop up even if I have schedules to choose from.
2. You should be able to add lectures with no sections -- e.g. ANTH 99. 
3. The schedule drop-down doesn't show the schedule quarter. (See the schedule drop-down on the "Add course" page)

2024-03-11 09:05 UTC, tallyhawley commented on frontend/package-lock.json
Don't push changes to package-lock.json

2024-03-13 00:05 UTC, Maria-Saucedo approved these changes
Checked Deployment on and was able to properly add courses now. LGTM
https://courses-maria-saucedo-dev.dokku-06.cs.ucsb.edu/

2024-03-13 00:24 UTC, tallyhawley approved these changes
Looks great to me :)

2024-03-13 00:24 UTC, merged

2024-03-20 21:59 UTC, aqiu28517 reviewed
It's a bit odd that the save changes button shows even when you have no schedules to add to, but otherwise great. LGTM.